#ifndef __GENERIC_CONFIG_H__
#define __GENERIC_CONFIG_H__
#undef EMULATE_X11_CODEC
#define EMULATE_X11_CODEC 1
#undef HAVE_BOOLEAN
#define HAVE_BOOLEAN 1
#undef HAVE_BZERO
#undef HAVE_INT16_T
#define HAVE_INT16_T 1
#undef HAVE_INT32_T
#define HAVE_INT32_T 1
#undef HAVE_INT64_T
#define HAVE_INT64_T 1
#undef HAVE_INT8_T
#define HAVE_INT8_T 1
#undef HAVE_IO_H
#define HAVE_IO_H 1
#undef HAVE_MEMMEM
#undef HAVE_OPENMP
#define HAVE_OPENMP 1
#undef HAVE_REALLOCF
#undef HAVE_SNPRINTF
#define HAVE_SNPRINTF 1
#undef HAVE_SSIZE_T
#define HAVE_SSIZE_T 1
#undef HAVE_STDINT_H
#define HAVE_STDINT_H 1
#undef HAVE_STDIO_H
#define HAVE_STDIO_H 1
#undef HAVE_STDLIB_H
#define HAVE_STDLIB_H 1
#undef HAVE_STRCASECMP
#define HAVE_STRCASECMP 1
#undef HAVE_STRCASESTR
#undef HAVE_STRINGS_H
#define HAVE_STRINGS_H 1
#undef HAVE_STRING_H
#define HAVE_STRING_H 1
#undef HAVE_STRNCASECMP
#define HAVE_STRNCASECMP 1
#undef HAVE_SYS_BITYPES_H
#undef HAVE_SYS_INTTYPES_H
#undef HAVE_SYS_TYPES_H
#define HAVE_SYS_TYPES_H 1
#undef HAVE_UINT16_T
#define HAVE_UINT16_T 1
#undef HAVE_UINT32_T
#define HAVE_UINT32_T 1
#undef HAVE_UINT64_T
#define HAVE_UINT64_T 1
#undef HAVE_UINT8_T
#define HAVE_UINT8_T 1
#undef HAVE_UNISTD_H
#define HAVE_UNISTD_H 1
#undef HAVE_U_INT8_T
#undef HAVE__SNPRINTF
#define HAVE__SNPRINTF 1
#undef PERL_PATCHLEVEL
#define PERL_PATCHLEVEL 30
#undef PERL_POLLUTE
#define PERL_POLLUTE 1
#undef PERL_SUBVERSION
#define PERL_SUBVERSION 2
#undef PRIMA_CORE
#define PRIMA_CORE 1
#undef PRIMA_PLATFORM_WINDOWS
#define PRIMA_PLATFORM_WINDOWS 1
#undef PRIMA_SUBVERSION
#define PRIMA_SUBVERSION 58
#undef PRIMA_VERSION
#define PRIMA_VERSION 1
#undef __INLINE__
#define __INLINE__ inline
#endif
